
language: nix
script: nix-build default.nix --argstr compiler $GHC_VERSION
env:
  - GHC_VERSION=ghc802

before_install:
  - >
      if ! echo "$TRAVIS_COMMIT_MESSAGE" \
         | grep -qvE  '\[(skip travis|travis skip)\]'
      then
        echo "[skip travis] has been found, exiting."
        exit
      fi
  - >
      if ! git diff --name-only $TRAVIS_COMMIT_RANGE \
         | grep -qvE '\.md$'
      then
        echo "Only docs were updated, stopping build process."
        exit
      fi

